import { useCallback, useEffect, useRef, useState } from 'react';
import { Bot, Info, Send, Eraser, Sparkles, Route, ScrollText } from 'lucide-react';
import { queryAnalyst } from '@/lib/api';
import type { AnalystResponse } from '@/lib/types';
import { apiErrorMessage } from '@/lib/errors';
import {
  badgeStyle,
  codeBlockStyle,
  fieldNote,
  inputStyle,
  primaryButton,
  secondaryButton,
} from '@/components/common/formStyles';

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  response?: AnalystResponse;
  error?: string;
  streaming?: boolean;
}

const SUGGESTED_QUESTIONS = [
  'Explain CPI transmission from airfares.',
  'What caused the recent airfare inflation movement?',
  'Which routes contribute most to CPI pressure?',
  'Forecast the national airfare index for the next 7 days.',
  'What is the current airfare pressure score?',
  'Explain the statutory composition of a BOM-DEL fare.',
];

const WELCOME_MESSAGE: ChatMessage = {
  id: 'welcome',
  role: 'assistant',
  content:
    'I am the VayuSutra AI Policy Analyst. I answer policy questions with deterministic evidence pulled from live APIx endpoints — nothing is generated by guesswork. Try one of the suggested questions below, or ask your own.',
};

let messageSeq = 0;
function nextMessageId(): string {
  messageSeq += 1;
  return `msg-${Date.now()}-${messageSeq}`;
}

export function AIPolicyAnalystPage() {
  const [messages, setMessages] = useState<ChatMessage[]>([WELCOME_MESSAGE]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [messages, loading]);

  const clearConversation = useCallback(() => {
    setMessages([WELCOME_MESSAGE]);
    setError(null);
  }, []);

  const sendQuestion = useCallback(
    async (question: string) => {
      const trimmed = question.trim();
      if (!trimmed || loading) return;
      setError(null);
      const userMessage: ChatMessage = { id: nextMessageId(), role: 'user', content: trimmed };
      const pendingId = nextMessageId();
      setMessages((prev) => [
        ...prev,
        userMessage,
        { id: pendingId, role: 'assistant', content: '', streaming: true },
      ]);
      setLoading(true);
      try {
        const res = await queryAnalyst({ question: trimmed, user_role: 'POLICY_ECONOMIST' });
        setMessages((prev) =>
          prev.map((m) =>
            m.id === pendingId
              ? {
                  id: m.id,
                  role: 'assistant',
                  content: `${res.answer_summary}\n\n${res.detailed_explanation}`.trim(),
                  response: res,
                  streaming: false,
                }
              : m
          )
        );
      } catch (err) {
        setMessages((prev) =>
          prev.map((m) =>
            m.id === pendingId
              ? { id: m.id, role: 'assistant', content: '', error: apiErrorMessage(err), streaming: false }
              : m
          )
        );
      } finally {
        setLoading(false);
      }
    },
    [loading]
  );

  const submitInput = useCallback(() => {
    void sendQuestion(input);
    setInput('');
  }, [input, sendQuestion]);
const renderAssistantBody = (message: ChatMessage) => {
    if (message.error) {
      return (
        <div
          style={{
            background: 'var(--semantic-error-bg)',
            border: '1px solid var(--semantic-error)',
            borderRadius: 'var(--radius-md)',
            padding: 'var(--space-3)',
            fontSize: 'var(--text-xs)',
            color: 'var(--semantic-error)',
          }}
        >
          {message.error}
        </div>
      );
    }
    if (message.streaming) {
      return <span className="analyst-typing" />;
    }
    const resp = message.response;
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--space-2)', alignItems: 'center' }}>
          {resp?.detected_intent && (
            <span style={{ ...badgeStyle, background: 'var(--brand-saffron-light)', color: 'var(--brand-saffron)' }}>
              INTENT: {resp.detected_intent}
            </span>
          )}
          {resp?.data_tag && (
            <span style={{ ...badgeStyle, background: 'var(--bg-tertiary)', color: 'var(--text-secondary)' }}>{resp.data_tag}</span>
          )}
        </div>
        <div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.65, fontSize: 'var(--text-sm)', color: 'var(--text-primary)' }}>
          {message.content}
        </div>
        {resp && (resp.affected_routes.length > 0 || resp.statutory_citations.length > 0) && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
            {resp.affected_routes.length > 0 && (
              <div>
                <div style={{ ...fieldNote, display: 'flex', alignItems: 'center', gap: 6, marginBottom: 'var(--space-2)' }}>
                  <Route size={13} /> Affected Routes
                </div>
                <div style={{ display: 'flex', gap: 'var(--space-2)', flexWrap: 'wrap' }}>
                  {resp.affected_routes.map((route) => (
                    <span
                      key={route}
                      style={{
                        padding: '4px 10px',
                        borderRadius: 'var(--radius-md)',
                        background: 'var(--bg-tertiary)',
                        border: '1px solid var(--border-primary)',
                        color: 'var(--text-primary)',
                        fontSize: 'var(--text-xs)',
                        fontFamily: 'var(--font-mono)',
                        fontWeight: 'var(--font-medium)',
                      }}
                    >
                      {route}
                    </span>
                  ))}
                </div>
              </div>
            )}
            {resp.statutory_citations.length > 0 && (
              <div>
                <div style={{ ...fieldNote, display: 'flex', alignItems: 'center', gap: 6, marginBottom: 'var(--space-2)' }}>
                  <ScrollText size={13} /> Statutory Citations
                </div>
                <ul style={{ margin: 0, paddingLeft: 'var(--space-5)', display: 'flex', flexDirection: 'column', gap: 4 }}>
                  {resp.statutory_citations.map((citation) => (
                    <li key={citation} style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                      {citation}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
        {resp && (
          <details>
            <summary style={{ fontSize: 'var(--text-xs)', fontWeight: 'var(--font-semibold)', color: 'var(--text-secondary)', cursor: 'pointer' }}>
              Numerical evidence + raw response
            </summary>
            <pre style={{ ...codeBlockStyle, marginTop: 'var(--space-2)' }}>{JSON.stringify({ numerical_evidence: resp.numerical_evidence, raw: resp }, null, 2)}</pre>
          </details>
        )}
      </div>
    );
  };
return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">AI Policy Analyst</h1>
          <p className="page-subtitle">
            Deterministic, evidence-grounded policy Q&A. Every answer is compiled from live
            VayuSutra APIx endpoints and cites affected DGCA routes plus statutory references.
          </p>
        </div>
        <div style={{ display: 'flex', gap: 'var(--space-2)', alignItems: 'center' }}>
          <button
            type="button"
            onClick={clearConversation}
            style={{ ...secondaryButton, alignItems: 'center' }}
          >
            <Eraser size={14} /> New conversation
          </button>
        </div>
      </div>

      <div className="data-source-strip">
        <Info size={14} style={{ color: 'var(--semantic-info)', flexShrink: 0 }} />
        <span>
          Questions are routed to <code>POST /api/v1/ai/analyst</code> with role{' '}
          <strong>POLICY_ECONOMIST</strong>. Intents are detected by pattern and answered from
          quantitative engine endpoints — no hallucinated numbers.
        </span>
      </div>

      {error && (
        <div
          style={{
            margin: '0 0 var(--space-4)',
            padding: 'var(--space-3)',
            borderRadius: 'var(--radius-md)',
            background: 'var(--semantic-error-bg)',
            fontSize: 'var(--text-xs)',
            color: 'var(--semantic-error)',
          }}
        >
          {error}
        </div>
      )}

      <div className="card" style={{ display: 'flex', flexDirection: 'column', height: 'max(520px, 60vh)' }}>
        <div
          ref={scrollRef}
          style={{
            flex: 1,
            overflowY: 'auto',
            padding: 'var(--space-5)',
            display: 'flex',
            flexDirection: 'column',
            gap: 'var(--space-4)',
          }}
        >
          {messages.map((message) => (
            <div
              key={message.id}
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: message.role === 'user' ? 'flex-end' : 'flex-start',
                maxWidth: '92%',
              }}
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 'var(--space-2)',
                  marginBottom: 'var(--space-1)',
                }}
              >
                {message.role === 'assistant' ? (
                  <Bot size={13} style={{ color: 'var(--brand-saffron)' }} />
                ) : (
                  <Sparkles size={13} style={{ color: 'var(--semantic-info)' }} />
                )}
                <span style={{ fontSize: 'var(--text-xs)', fontWeight: 'var(--font-semibold)', color: 'var(--text-tertiary)' }}>
                  {message.role === 'assistant' ? 'AI POLICY ANALYST' : 'YOU'}
                </span>
              </div>
<div
                style={{
                  borderRadius: message.role === 'user' ? 'var(--radius-lg) var(--radius-lg) var(--radius-sm) var(--radius-lg)' : 'var(--radius-lg) var(--radius-lg) var(--radius-lg) var(--radius-sm)',
                  padding: 'var(--space-3) var(--space-4)',
                  background: message.role === 'user' ? 'var(--bg-tertiary)' : 'var(--bg-card)',
                  border: message.role === 'user' ? 'none' : '1px solid var(--border-primary)',
                  fontSize: 'var(--text-sm)',
                  color: 'var(--text-primary)',
                  minWidth: 0,
                  width: '100%',
                }}
              >
                {message.role === 'user' ? (
                  <span style={{ whiteSpace: 'pre-wrap', lineHeight: 1.6 }}>{message.content}</span>
                ) : (
                  renderAssistantBody(message)
                )}
              </div>
            </div>
          ))}
          {loading && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)', fontSize: 'var(--text-xs)', color: 'var(--text-tertiary)' }}>
              <Bot size={13} style={{ color: 'var(--brand-saffron)' }} />
              Analyst is computing a grounded answer…
            </div>
          )}
        </div>

        <div
          style={{
            borderTop: '1px solid var(--border-primary)',
            padding: 'var(--space-4)',
            display: 'flex',
            flexDirection: 'column',
            gap: 'var(--space-3)',
          }}
        >
          <div style={{ display: 'flex', gap: 'var(--space-2)', flexWrap: 'wrap' }}>
            <Sparkles size={14} style={{ color: 'var(--text-tertiary)', marginTop: 2 }} />
            {SUGGESTED_QUESTIONS.map((q) => (
              <button
                key={q}
                type="button"
                onClick={() => void sendQuestion(q)}
                disabled={loading}
                style={{
                  padding: '4px 10px',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid var(--border-primary)',
                  background: 'var(--bg-tertiary)',
                  color: 'var(--text-secondary)',
                  fontSize: 'var(--text-xs)',
                  cursor: loading ? 'default' : 'pointer',
                  opacity: loading ? 0.6 : 1,
                }}
              >
                {q}
              </button>
            ))}
          </div>
          <div style={{ display: 'flex', gap: 'var(--space-3)', alignItems: 'stretch' }}>
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') submitInput();
              }}
              placeholder="Ask a policy question…"
              disabled={loading}
              style={{ ...inputStyle, fontFamily: 'inherit', flex: 1 }}
            />
            <button
              type="button"
              onClick={submitInput}
              disabled={loading || !input.trim()}
              style={{ ...primaryButton, opacity: loading || !input.trim() ? 0.6 : 1 }}
            >
              {loading ? <span className="analyst-typing-dot" /> : <Send size={15} />}
              {loading ? 'Analyzing' : 'Send'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}